### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'mergecap'

### ISSUE THREAD

**Issue by CoderWeiLee** [Tommrodrigues/WiFiCrackPy#2]
when it notice me to Select a network to crack and then i select one,a moment later it show this notice:
FileNotFoundError: [Errno 2] No such file or directory: 'mergecap'
how can i fix it?

**Comment by Tommrodrigues** [comment]
Hi there, please see the `Prerequisites` section of the `README.md`.

You must have `mergecap` installed, which comes as part of the Wireshark application.

You can check if you have successfully installed it by running `mergecap` in the terminal.
